# 所有环境公用的配置属性
# spring boot配置文件
server:
  port: 8081
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# 描述应用
info:
  app-name: spring-boot-demo
  author: waitfor
  email: xxx@email
spring:
  profiles:
    active: dev
---
# profile=x的专用属性，也是某个环境下的专用属性
# 开发环境
spring: 
  profiles: dev
---
# profile=y的专用属性，也是某个环境下的专用属性
# 生产环境
spring: 
  profiles: prod
server: 
  tomcat:
    max-threads: 300
    max-connections: 1000
